version: '3.1'

services:
  front_server:
    image: httpd:2.4
    volumes:
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./build:/usr/local/apache2/htdocs/
    ports:
      - 9000:80